### ISSUE TITLE
Does not work in Mac

### ISSUE THREAD

**Issue by Tubaleviao** [larrybahr/windows-network-drive#15] opened 2021-02-17 21:36 UTC
Hey, this would be really useful if we could also run it on Mac or Linux. Any development happening on this point?

**Comment by larrybahr** [comment] 2021-02-17 22:39
duplicate of #11 
I still plan on making a single solution that will work with Windows, Mac, and Linux; but have not had time yet.

**Closed as completed by larrybahr** 2021-02-17 22:39 UTC

**Comment by Tubaleviao** [comment] 2021-02-17 23:08
So why don't you leave the issue open? If it's not there, not one will be able to help you

**Comment by larrybahr** [comment] 2021-02-18 05:49
As stated in the linked issue 

> Since this is a Windows specific lib I do not plan to support Mac directly. At some point I would like to try to merge the Mac/Linux network mounting code into one solution so there is a single package that can be used on all the platforms.

I do not want to add scope creep to this package. I would rather each module do one thing well and have a wrapper package that normalizes the interfaces. For that reason I created https://github.com/larrybahr/universal-network-drive

My goal is to get it to the point of using both the windows (this repo) and mac package over the next week. Then at some point in the future try to add a linux-network-drive package and integrate that into the universal-network-drive. 

If you want to help PR are welcome. If you are not sure where to get started, you could work on the linux-network-drive port.
